version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/project
    overwrite: yes
permissions:
  - object: /home/ubuntu/project
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: script/deploy.sh
      timeout: 600
      runas: root