name: book-management-ci

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.4'

      - name: ls
        run: echo "output = " >> ${GITHUB_OUTPUT}

      - name: Build with Gradle
        run: clean build -x test

  s3:
    needs: build
    name: S3 Upload
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Make Zip File
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload File to AWS S3
        run: |
          aws s3 cp ./$GITHUB_SHA.zip s3://book-management-1/

      - name: Code Deploy
        run: aws deploy create-deployment --application-name book-management --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name book-group --s3-location bucket=book-management-1,bundleType=zip,key=$GITHUB_SHA.zip


