name: book-management-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: pwd
        run: ls && pwd
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
